### ISSUE TITLE
Create a Code of Conduct

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/open-source#1]
A Code of Conduct is now an expected document for any good open source project. And the most important projects already have one.

This document describes an expected behavior based on good will, openness and respect, for discussions on all the communication channels of the PrestaShop project, between all the people:
- Online, e.g on the forums, GitHub, or social networks
- In real life, e.g during events and meetups
- With the many languages, cultures and origins of the community
 
A Code of Conduct must be enforceable.

Todo:
- [x] write a french version with a lawyer
- [x] make an english translation
- [x] review of both version by a lawyer
- [x] submit to the community for feedback
- [x] apply it on communication channels

**Comment by ttoine** [comment]
Work in progress, a draft is being written on Google Doc, in French and in English.

When this first version will handle the different use case the CoC must handle, it will be published and open to comments.

**Comment by xibe** [comment]
That's great news! I tried to put a CoC in place during my time, but didn't get support from the head management. I'm glad the new management embraces the 21st Century -- I never expected less of them anyway :)

**Comment by ttoine** [comment]
Actually, the people to convince now are some forum users who are currently have a bad behavior. Particularly, on the french part of the forums...

**Comment by ttoine** [comment]
The prototype is online and open to discussion, in English and in French
Please open an issue (preferred) or a pull request

https://github.com/PrestaShop/open-source/tree/master/code-of-conduct

**Comment by ttoine** [comment]
https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md
