### ISSUE TITLE
Publish demos on a public platform

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/open-source#10]
Currently, the demo-retro is only for the PrestaShop company employees. And even if the demos are recorded, they are only available internally.

In order to show how the work of the PM and dev teams is advancing, it would be great to publish the videos of the demo on a public platform.

Todo:
- [x] record demos
- [x] create a dedicated channel to host the videos (wip)
- [x] upload the videos and communicate about it

**Comment by ttoine** [comment]
A discussion is in progress in order to open a dedicated YouTube channel for that.
@eternoendless

**Comment by matks** [comment]
Hello @ttoine I think we can close this issue 😄  our demos are now published on https://www.youtube.com/channel/UCchgBHHhl5Vu7HgjrzpvVQQ

**Comment by ttoine** [comment]
This is great to see that it's been done and now a regular event :-)
