### ISSUE TITLE
Lighten the committer application process

### ISSUE THREAD

**Issue by matks** [PrestaShop/open-source#100]
Hello everyone,

## Let's start inviting committers to help us to review Pull Requests

The [committers](https://www.prestashop-project.org/maintainers-guide/how-to-become-a-committer/) role was introduced to help us on the review effort. This is an idea we found from this [NodeJS article](https://medium.com/the-node-js-collection/healthy-open-source-967fa8be7951). If you have not read the article yet, please do 👍 it brings context for this topic and is a nice overview of another open source project.

I believe the maintainers team of PrestaShop currently struggle to process all incoming contributions (= pull requests) on the prestashop project. We have always be struggling 😅 , but these last months even more. It is probably also is related to part of the team focusing their time on the [rush to finish 8.0.0 feature freeze](https://github.com/PrestaShop/PrestaShop/issues/26427).

Even if we consider review workforce will rise again after 8.0.0 feature freeze, I think we should move forward and start inviting people to become committers. This will help current maintainers to handle the incoming contributions (for the code review part) and as written in the NodeJS article it is anyway a healthy practice to have committers and share the burden of code review.

The first people we'll probably look for are long-term contributors who have contributed multiple time over years to the project and then demonstrated their ability to verify whether a given contribution is valid. We have plenty around 😁 and this would give them the opportunity to become more involved in the project - if they want to obviously.

But if you read the NodeJS article, you'll see they mention they don't wait for multiple months and contributions to invite people to become committers:

> All contributors who land a non-trivial contribution should be on-boarded in a timely manner, and added as a committer, and be given write access to the repository.

The idea carried by this article is "don't wait weeks to be 100% sure before allowing someone to become a committer, as soon as they contribute, grant them the rights and carry on".

That is an interesting idea 😊 .

## Inviting someone to be a committer as soon as he/she has 1 contribution merged

Inviting someone to be a committer as soon as he/she has 1 contribution merged sounds like a crazy idea, right?

But let's take a look back in the past. Do you remember 2017 and 2018 ? At this time the prestashop project and the prestashop company were 100% merged. Only PrestaShop SA employees could become maintainers, and everything was done by the company in private. No open source slack, no public demos, not daily ZIP being built on https://nightly.prestashop.com/ .

At this time, on their first day of work, new member of the PrestaShop SA Core team would be granted maintainer rights on the project and ask to start doing code reviews. At day one. This is what happened to me 😅  hoho that was a bit scary. But at least new hires of PrestaShop SA Core team were able to help with the review effort from day one.

Years later, the project has become more mature and we now have a quite good [application process](https://www.prestashop-project.org/maintainers-guide/how-to-become-a-maintainer/) for maintainers that allow anybody, not only PrestaShop SA employees, to apply for the maintainer position and be granted maintainer rights.

But now it's a lot slower to onboard new maintainers 👍 because we cannot grant maintainer rights to someone who does not get approved by the group. And when I introduced the committers role to you, I suggested an application process a little lighter, but still heavy.

I think the committer application process I wrote is too heavy 🔩 and prevents us from on-boarding committers in a quick and efficient manner. I actually think we could choose a system simpler. My suggestion is:

- Any contributor (= 1 PR merged) can apply for the committer position
- If 3 maintainers approve the application the contributor is granted committers rights and a 90-day trial period begins

Simple and easy. It means any contributor who has 1 PR merged and is trusted by 3 maintainers can become [committer](https://www.prestashop-project.org/maintainers-guide/how-to-become-a-committer/).

So this is my suggestion: lighten the committer application process in order to allow us to onboard plenty of people we trust and help us with the review effort, following [the NodeJS example](https://medium.com/the-node-js-collection/healthy-open-source-967fa8be7951). And this is actually close to what we used to do in 2018 and 2019, before we had the maintainer application process and I dont remember big issues from that.

### Onboarding people too quick could allow people not suitable / not prepared / not skilled to become committers and do bad to the project

First, the only thing a bad committer could do is perform bad code reviews.
- committers cannot vote on ADR
- committers alone cannot approve a PR, a maintainer approval is required
- 
So the "risk" of bad work being done is limited to code review.

Second, committers still need 3 maintainers to trust them enough 😄 so the risk is even more limited.

Third, I remember that in 2018 on my first day at PrestaShop, when I was granted review rights as a PrestaShop employee, I did not purposefully approve Pull Requests I was not able to review. When I considered I was not skilled / ready to say "this PR is good" or "this PR is not valid" I just said nothing. I think the same will happen with committers: they will only approve what they are confident to review, and they will not use their committer rights unwisely. That is what I expect from someone I trust, to know when they can help and when they should not act.

### What happens if a committer is doing a poor job and does not improve

Just like I suggest to lighten the committer process, I also suggest to lighten the removal process:

- If some maintainers believe a committer is not reviewing correctly, maintainers discuss the matter and can simply remove the committer rights with a simple majority vote.

## Conclusion

Thank you for reading all this 😅 so if I try to summarize this big text: I think I introduced a process too heavy for a role not so critical.

The level of requirement we have for maintainers is relevant because of the responsibilities that come with the role, but the committer role requires less involvement and thus could be more permissive, allowing us to onboard quickly people willing to help us on the code review effort.

This is inspired by a NodeJS maintainers idea, and I guess they quite know what they do 😄 . And also we were a lot more permissive in 2018 / 2019 when we would grant maintainer rights to new PrestaShop SA hires on their first day, and we did not encounter big issues from that.

**Comment by matthieu-rolland** [comment]
I love the idea! 

At first, I read [your PR](https://github.com/PrestaShop/open-source/pull/101/files) and kinda freaked out when I saw all the red parts 😅  (all the conditions that we removed)

but reading the NodeJS article, the philosophy behind this approach and how it would apply to our project is quite reassuring, the negative effects seem limited. 

Also, given the situation we have to try something anyway, if for some reason there are real issues with this approach, we can adjust as we face them.
