### ISSUE TITLE
[Request to become a PrestaShop committer] okom3pom

### ISSUE THREAD

**Issue by okom3pom** [PrestaShop/open-source#103]
Hello Team,

I saw that new positions were open to participate in the organization.
I would be interested to join the Commiter team or why not Scoped Maintainers.
First of all you will have understood that I am not very good in English but I think that with the current tools I should be able to do it.

What do you need to know about me?

**As you ask on https://www.prestashop-project.org/maintainers-guide/how-to-become-a-committer/** 

https://github.com/PrestaShop/PrestaShop/pull/27762

https://github.com/PrestaShop/PrestaShop/pull/27662

https://github.com/PrestaShop/PrestaShop/pull/27442

https://github.com/PrestaShop/PrestaShop/pull/27408

https://github.com/PrestaShop/PrestaShop/pull/26246

**I am starting slowly with vuejs :** 

https://github.com/PrestaShop/TopContributors/pull/76

**Slack ?**

I'm not very active on the open source slack because of my english level, but I'm also part of the 1M club

Finally I am an e-merchant who can bring an extra vision to the project that i can share 

Sorry again for the quality of my English

**Comment by mickaelandrieu** [comment]
This could be amazing to have a merchant as part of the open source team : Thomas is a real nice guy, always eager to give a hand to whom who ask for.

He also helped me practicing some data analysis and data science using real shop data, and his english is not that bad for a french 🤣

**Comment by Hlavtox** [comment]
This guy knows what he is doing! 🚀

**Comment by NeOMakinG** [comment]
Full support

**Comment by Progi1984** [comment]
It's an approval on my side.

**Comment by eternoendless** [comment]
We are happy to have you as a commuter @okom3pom ! 🎉 

We'll invite you to the organization and grant you committer rights soon.

**Comment by okom3pom** [comment]
Thanks to the team! I hope I can bring my experience as a merchant. See you soon
