### ISSUE TITLE
[Suggestion] Add a new role : Technical documentation managers

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/open-source#104]
Regarding a thread earlier this day we had with somes members of the community, I said something as : "I agree, the project need a technical documentation lead", in order to check the missing part of the documentation and manage the reviews and complete it if possible.

As I know and as it's writed inside the project organization (https://www.prestashop-project.org/maintainers-guide/project-organization/#user-documentation-managers) ; we've User Documentation Managers.

Why not technical documentation managers ? :)

**Comment by eternoendless** [comment]
Yes, of course, and we actually have a [job opening for that role](https://www.welcometothejungle.com/en/companies/prestashop/jobs/tech-content-manager-open-source_paris_PREST_JWJlbag)!
