### ISSUE TITLE
Permanent redirect prestashop.com sites to prestashop-project.org sites

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/open-source#119]
Please redirect in 301 (Permanent)
https://devdocs.prestashop.com/
https://build.prestashop.com/
to
https://build.prestashop-project.org/
https://devdocs.prestashop-project.org/

Duplicate content is very bad for prestashop-project.org ranking in search engine.

**Comment by eternoendless** [comment]
Fixed! Comments on build might take some hours to re appear.
