### ISSUE TITLE
Create a technical event with content in english and a call for paper

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/open-source#12]
Many possibilities here:
- Create a dedicated event
- Open a technical track on one of our current event (Varsovie as already content in english)
- Create a track on an other event, like Paris Open Source Summit

What is important here is to have a call for paper and a selection committee, in order to give the voice to community (of course employees of the PrestaShop company should propose talks too). The idea is to follow the way other big open source communities are doing: the community is speaking to the community.

**Comment by matks** [comment]
Done by https://build.prestashop-project.org/news/2023/prestashop-developer-conference-2023/
