### ISSUE TITLE
[Request to become a PrestaShop committer] FabienPapet

### ISSUE THREAD

**Issue by FabienPapet** [PrestaShop/open-source#121]
👋 Prestashop open-source community.

I'm happy to ask you about my wish to become a prestashop committer.

For those who don't know me, I'm started working in the Prestashop SA Company in July, and for now I'm mainly fixing bugs and (trying to) improve DX on the project. I also want to improve Prestashop migration into Symfony.

Thank you for reading !

**Comment by matks** [comment]
Hello @FabienPapet after working with you for almost 3 months now I think you can be a great committer indeed 😉 

I approve this application

**Comment by kpodemski** [comment]
Hey Fabien 👋 

You're doing a great job. It'll be great to have you as a committer.

**Comment by eternoendless** [comment]
You're in 😄
