### ISSUE TITLE
[Request to become a PrestaShop committer] nicosomb

### ISSUE THREAD

**Issue by nicosomb** [PrestaShop/open-source#137]
Hello PrestaShop community!

I started at PrestaShop in september. I work on PrestaShop bugs and on new features (for example, new image formats https://github.com/PrestaShop/PrestaShop/issues/27264). 
I'm quite new 👶 on the project but I'm quite old 👴 in opensource ecosystem (mainly with [wallabag project](https://github.com/wallabag/wallabag)). 

That's why I'm happy to ask you about my wish to become a PrestaShop committer.

Have a nice day!

**Comment by matks** [comment]
Hello @nicosomb really cool news 😄 I approve this application

**Comment by kpodemski** [comment]
+1 approval

**Comment by NeOMakinG** [comment]
Agree 🍬

**Comment by matks** [comment]
Dear @nicosomb  I quote [the maintainer guide](https://www.prestashop-project.org/maintainers-guide/how-to-become-a-committer/):

> If three maintainers approve the application, the new committer is approved.

You are consequently approved as committer, welcome in the team! ❤️

**Comment by nicosomb** [comment]
Thank you ❤️

**Comment by PrestaEdit** [comment]
And here we go again : same as https://github.com/PrestaShop/open-source/issues/139#issuecomment-1317444169
