### ISSUE TITLE
Lartist's application to get a PrestaShop committer

### ISSUE THREAD

**Issue by lartist** [PrestaShop/open-source#138]
Hi everyone,

It has been almost 2 months I'm implicated in the PrestaShop Open Source community. I started with fixing bug so that I appropriate the code base. Now that I'm more comfortable with this, I do daily code reviews, work on new features, still fix bug, update developper XP such as CI improvement, auto-wiring and so forth.

For this reason, I'm glad to apply for the committer role.

Mainteners it's up to you :)

**Comment by matks** [comment]
Hello @lartist happy to see you apply for the role, I approve this application 🎉

**Comment by kpodemski** [comment]
+1 approval

**Comment by NeOMakinG** [comment]
Agree 🍬

**Comment by lartist** [comment]
Thank you all 😄

**Comment by PrestaEdit** [comment]
Of course, what I say there is the same for this : https://github.com/PrestaShop/open-source/issues/139#issuecomment-1317444169
