### ISSUE TITLE
[Request to become a PrestaShop committer] mflasquin

### ISSUE THREAD

**Issue by mflasquin** [PrestaShop/open-source#139]
Hi PrestaShop community ! 👋

I started to work for PrestaShop SA in September and I've made some to improvments and bug fixes on Prestashop Core repository and 
modules like PS Shop Creator or PS example modules. Moreover, I try to help to go forward as a PR reviewer. Also I will work on the next few weeks on the new PS API !

So I'm glad to ask you about make me a committer :smile:

**Comment by matks** [comment]
Hello @mflasquin I'm really happy seeing this message -> I approve the application 😄

**Comment by kpodemski** [comment]
+1 approval

**Comment by matthieu-rolland** [comment]
it's a yes :+1

**Comment by matks** [comment]
Dear @mflasquin I quote [the maintainer guide](https://www.prestashop-project.org/maintainers-guide/how-to-become-a-committer/):

> If three maintainers approve the application, the new committer is approved.

You are consequently approved as committer, welcome in the team! ❤️

**Comment by PrestaEdit** [comment]
September, in PrestaShop SA.
November, in PrestaShop OS.

I really don't undestand why there is only SA employees that allow to become somes to be commiters on a project as this one, especially regarding this timeline.

Are you not able to do your job as contributor, really need to be a commiter for that ? 🤔

**Comment by matks** [comment]
@PrestaEdit

> I really don’t undestand why there is only SA employees that allow to become somes to be commiters on a project as this one, especially regarding this timeline.

This is far from reality. The project have great committers that have never worked for PrestaShop SA:
- Mahmoud Parvazi ([@mparvazi](https://github.com/mparvazi))
- Thomas Roux ([@okom3pom](https://github.com/okom3pom))
- Tomasz Zając ([@SharakPL](https://github.com/SharakPL))

Your maintainer application was rejected but we clearly said we would be happy to accept you as a committer. If you had accepted the offer you would be one more committer not paid by PrestaShop SA. Krystian [just suggested to Hlavtox](https://github.com/PrestaShop/open-source/issues/140#issuecomment-1312587634) to become a committer. As you can see nothing blocks people that are not paid by PrestaShop SA from becoming committers the project as long as they fit the role.

I personally tried to motivate someone that is not related to PrestaShop SA  last month that I think could be a great committer but this person felt not ready yet, maybe for 2023.
