### ISSUE TITLE
Make the software installable without the PrestaShop company server

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/open-source#14]
The open source project should be installable without dependency of the PrestaShop company servers. If they are available to provide other features and content, this is a plus. But it must not have an impact on usability, nor on the performance of the software.

See also: PrestaShop/PrestaShop#10456

**Comment by ttoine** [comment]
See also: https://github.com/PrestaShop/PrestaShop/issues/12851

**Comment by matks** [comment]
See 'Split Open-source/Corporate' in https://github.com/PrestaShop/PrestaShop/issues/24111

**Comment by matks** [comment]
Done in PrestaShop 8.0.0
