### ISSUE TITLE
[Request to convert to comitter] Hlavtox

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/open-source#140]
Previous request - https://github.com/PrestaShop/open-source/issues/81

_________________

Hi guys, I would like to extend up on my maintainer status and gain rights to the whole project. We never got to assigning full rights for my position and it's quite limiting sometimes, so, in order not to complicate things. :-)

### What I would like to do
- Approve PRs in core repository. I have quite a bit of knowledge of historic core inner workings and I can see dangerous side of things quite well. The same goes for performance related PRs.
- I want to help with issue and PR management, mainly have ability to assign labels there.
- I want to help with dev QA of PRs.

### What changed from last time
Well, some time passed, a lot of work and PRs had been done and I gained some more experience with backend coding. I learned things that were a mystery before - I can work with symfony controllers, use dependency injection, use symfony forms etc. Not a pro dev, but I can do almost anything. Also, I can now actually work with and create new tests, absolutely unreal a year ago. :-)))

**Some of my last nice PRs**
- https://github.com/PrestaShop/PrestaShop/pull/29678/files
- https://github.com/PrestaShop/PrestaShop/pull/29411/files
- https://github.com/PrestaShop/PrestaShop/pull/28183/files
- https://github.com/PrestaShop/PrestaShop/pull/27292/files
and 100 others

**Comment by kpodemski** [comment]
I think it's the same as with Jonathan's application. It would be better, for now, for you to become a committer as the project structure will change, and ultimately, you have almost the same rights as the maintainer 👍 

So, if you are interested, you'll have my approval for a committer role as you are a huge help for the project already, and with committers rights, we could speed up things.

**Comment by Hlavtox** [comment]
Well, I already am a maintainer no? I should have got rights to the repository originally, so there should be no change no?

**Comment by kpodemski** [comment]
Daniel, come on ;) https://www.prestashop-project.org/maintainers-guide/project-organization/#scoped-maintainers

**Comment by Hlavtox** [comment]
What I said in my original request:

> (if possible) I want to be able to approve SEO, UX and performance related PRs in the core respository, thus improve the quality of the frontend. Don't know if this is even possible, maybe not, but you can try it and kick me out if I sniff my nose where I should not. 👍

In the link you sent:

> If the scope is one or multiple repositories, maintainers rights are granted only on these repositories. If the scope is larger (example: being in charge of a folder inside a repository) maintainer rights are granted on the repository and the scoped maintainer is trusted not to abuse.

So?

**Comment by leemyongpakvn** [comment]
I feel safer with atomiix's bike :satisfied:

**Comment by kpodemski** [comment]
@Hlavtox, as we discussed on Slack, the project's structure will change, so you have my vote for the committer role because, ultimately, as a committer, you would have proper rights to do all this:

> Approve PRs in core repository. I have quite a bit of knowledge of historic core inner workings and I can see dangerous side of things quite well. The same goes for performance related PRs.
I want to help with issue and PR management, mainly have ability to assign labels there.
I want to help with dev QA of PRs.

**Comment by matks** [comment]
> I feel safer with atomiix's bike 😆

This needs some explanations @leemyongpakvn 😄

**Comment by leemyongpakvn** [comment]
Don't worry, just my personal feeling, I'm afraid of high speed car, high speed high risk. NeOMakinG's leaf hat looks safe too. :) Btw, I strongly support the candidate's third _Like-to-do_.

**Comment by matks** [comment]
Hi @Hlavtox and thank you for your request 😄 

Following [our rules](https://devdocs.prestashop.com/1.7/project/maintainers-guide/how-to-become-a-maintainer/), I guess now will start discussions with current maintainers on this issue about any topic we wish to explore regarding this request

Some maintainers might be on holidays right now so we will need to be patient and wait a little so they can have the chance to chat with you before moving on to the voting phase 😉

**Comment by NeOMakinG** [comment]
> @atomiix & @matks Don't worry, just my personal feeling, I'm afraid of high speed car, as high speed high risk. NeOMakinG's leaf hat looks safe too. :) Btw, I strongly support the candidate's third _Like-to-do_ in any role.

Feel free to send me any hats as a gift 🎩

**Comment by Hlavtox** [comment]
What is going on here ffs 🤣🤣

**Comment by matks** [comment]
Hello @Hlavtox well it's time I speak up. I will be fully transparent and tell you what I honestly think.

I believe you have the skills, no doubt about that. You also have the motivation and the will. You clearly do a lot of work on the project right now and your contributions have greatly increased the project value.

But, nothing new here, I'm scared of how you talk 😅 .

We know you are 'raw': you don't put the little nice & polite words that us western people seem to like. You don't add plenty emojis 😄 like I do, you speak your mind, bluntly, you're direct, you don't care about writing it in a better way. As you mentioned when we discussed, you're not used to collaborate with other people that don't have the same mindset as you.

I'm afraid that one day you're going to go too far and breach the Code of Conduct or trigger a drama. And if you're a committer, consequences will be more costly than if you are a scoped maintainer.

I am sorry. I value your work, your developer skills, your strictness, your focus on performance, but I'm afraid having you in the committer team and one day you might be flame-throwing a contributor.

**Comment by matthieu-rolland** [comment]
I vote positively 👍 

About the "tone" issue, I trust @Hlavtox to communicate respectfully in the future.

**Comment by eternoendless** [comment]
Makes complete sense to me.

Congratulations on becoming a committer! As Matthieu, I trust you to work on your communication skills ;)

**Comment by Hlavtox** [comment]
I will @matthieu-rolland @eternoendless! 🙏 Thank you!!!
