### ISSUE TITLE
Group old issues of the same topics

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/open-source#15]
A good way to track a topic is to group old issues of the same topic in a new one (call that Epic, or Story or whatever). This will help to track and set priorities in project management.

This will also show that old issues are not forgotten and reinforce the interest for user to spend time to report them.

Finally, it makes it more easy for users to find those issues if they are concerned, to document them, and for a contributor, to provide an eventual "global" fix.

**Comment by ttoine** [comment]
Done or being currently done by the PM team and the Core team.

**Comment by toutantic** [comment]
https://github.com/PrestaShop/PrestaShop/labels/Epic
