### ISSUE TITLE
[Request to become a PrestaShop maintainer] Nesrine ABDMOULEH

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/open-source#158]
## About me

I am Nesrine ABDMOULEH a QA automation engineer at Prestashop, I would like to become a UI Tests maintainer.

6 years of contribution to the prestashop OS project :star_struck: 

From june 2017 to July 2021, I was a member of the QA team in service from Tunisia and since October 2021, I become a member of the internal QA team of the company PrestaShop in Paris where I held the following roles:

- Review PRs of UI tests
- Create new UI tests and maintain old ones
- Adapt the UI tests with the new features of the application and all versions from PS 1.7
- Ensure the quality of tests by the continuous evolution
- The monitoring of the nightly (Fixing problems and finding bugs)
- Run all campaigns on same pull request and fix the errors
- Training & support for new QA automation team members
- Testing and validation of PRs
- Testing and validation of modules

Thanks to the support, help and trust of @boubkerbribri I become more responsible for the automated tests of OS projet :pray: 

## Why do I want to become a maintainer 

- I had the opportunity to integrate the project based on its first lines of code, I welcomed many new arrivals by offering them presentations and support to develop their skills. And I would like to expand this sharing with the contributors through the exchanges that I will initiate on their PRs as a maintainer.

- My important contribution to the structure of the project, the choice of existing tools and frameworks will be an asset to promote the development of the project within the community, to ensure the continuity of quality and to highlight our know-how in order to facilitate external contributions.

- I have evolved in Prestashop as much as the project has evolved, I have provided internal responsibilities, and now I feel indebted to assume my responsibilities with external contributors.

## Contributions

You can find the details about my contributions [here](https://contributors.prestashop-project.org/#nesrineabdmouleh)

![Capture d’écran de 2023-02-13 10-24-36](https://user-images.githubusercontent.com/24647495/218689775-a7a439cb-9a0f-41b1-9f6d-2555c75a997a.png)

I hope you will find in these words the conviction to crown me with the role of maintainer !
Thank you for your interest in my issue :blush:

**Comment by Progi1984** [comment]
After discussion with @kpodemski, there’s a voting phase planned to March 1st.

**Comment by boubkerbribri** [comment]
Hello @nesrineabdmouleh 
Congratulations on becoming a UI-tests Maintainers :tada: :tada:. Welcome in the team !

**Comment by kpodemski** [comment]
The voting phase has ended. Welcome to the maintainer's team @nesrineabdmouleh :)
