### ISSUE TITLE
[Request to become a PrestaShop committer] 0x346e3730

### ISSUE THREAD

**Issue by 0x346e3730** [PrestaShop/open-source#160]
👋🏼 PrestaShop community,

I'm a freelancer that started working with PrestaShop SA in October of 2022 and I think that now is a good time to ask to become a committer on the OpenSource project.
I've been working on bugs, the documentation, the CI... and I've been reviewing PRs to get a glance of PrestaShop and understand it better. I'm now mainly working on migrating backoffice pages to Symfony and think I understand PrestaShop enough to become committer.

Thank you for reading :)

**Comment by kpodemski** [comment]
You have my vote ✅ keep up the good work

**Comment by matks** [comment]
That's a 👍 for me too 😄

**Comment by matthieu-rolland** [comment]
voted !

**Comment by matks** [comment]
Dear @0x346e3730  I quote [the maintainer guide](https://www.prestashop-project.org/maintainers-guide/how-to-become-a-committer/):

> If three maintainers approve the application, the new committer is approved.

You are consequently approved as committer, welcome in the team! ❤️
