### ISSUE TITLE
Open all issues, including for native modules, on the main repository

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/open-source#17]
Currently, a few modules have a separated issue board.

To make it more easy to track issues for project management, and to make only one place for users, the good way is to configure the repositories so issues are created in only one place.

This place should be the main repository.

Also, be sure that readme.md and devdoc tells where to open new issues.

**Comment by matks** [comment]
I think this is done. Every native modules repository has its "issues" section closed and we ask people to open issues on main repository.

**Comment by ttoine** [comment]
Good to know !
Let's close this one, then.
