### ISSUE TITLE
[Request to become a PrestaShop committer] boherm

### ISSUE THREAD

**Issue by boherm** [PrestaShop/open-source#180]
Hi everyone! 👋

Few months ago, I started to work for PrestaShop SA, for PrestaShop project and some PrestaShop modules.
My understanding of this project architecture is better day after days.

After some bug fixes, some work on improvements, some migrations from legacy to Symfony, I think that can be the good time to ask to become a PrestaShop committer.

I will be happy to be part of the committer team and help you improve this great project!

Have a nice day! 😉

**Comment by matks** [comment]
Really happy to see this application 😄 it's a YES from me

**Comment by 0x346e3730** [comment]
![image](https://media.tenor.com/w7xtCCEEW_kAAAAC/im-gonna-say-yes-simon-cowell.gif)

**Comment by matthieu-rolland** [comment]
YES

**Comment by jolelievre** [comment]
![image](https://media.giphy.com/media/VUOMN3AJbxSeY/giphy.gif)
