### ISSUE TITLE
Anybody should be able to build from source and make a release

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/open-source#19]
Currently, only core devs, employees of the PrestaShop company can build and make a release. At one point, people from the community should be able to do it too.

Also, continuous improvement in the devdocs about how to build in the project would be great.

**Comment by matks** [comment]
Everything is explained here https://github.com/PrestaShop/PrestaShop/blob/develop/tools/build/README.md

**Comment by ttoine** [comment]
I would say that as each time there is a new release, this is not a straightforward process, this is not a complete tutorial. It's not just about build, it's also the release process that should be public.

**Comment by matks** [comment]
But we will never allow "anybody" to make a release ?

Right now "anybody can build" => it's true

We can document what we do to make a release, but it will never be available to anybody, it will be a Core Team maintainer only.

To do a release:
- We update the Changelog file, Contributors file and the Version number
- We create a git tag on github
- We create the build using the tool above
- QA validates it
- We upload the build on prestashop.com and github (we also publish a release on github)
- We update the Translations packages
- We update the Upgrade API informations
- We update docker images https://github.com/PrestaShop/docker

**Comment by ttoine** [comment]
All tasks in that list must be documented for transparency purpose, even if of course, only core maintainers will do it. (of course it is best practice to hide confidential information)

This way, the work needed to transform a build into a release is known, the effort is understandable, and it is possible to get improvements and ideas from the community.

Also, it is very interesting for people who build a kind of distribution for their customers needs: they will have access to all the information needed to find all the resources for a version, or to generate what they need if they add stuff to the project's basics.

**Comment by matks** [comment]
I think this item is now finished. The complete release documentation is available on https://devdocs.prestashop.com/1.7/project/maintainers-guide/releasing-prestashop/

**Comment by ttoine** [comment]
I would wait for the first full open source release of the software. At this stage, any maintainer will be able to build a release. Currently, there are links with the PrestaShop company, and steps that only employees can do.

**Comment by matks** [comment]
PrestaShop 8.0.0 the first full open source release is now live 🎉 so this item is done.
