### ISSUE TITLE
[Request to become a PrestaShop committer] tleon

### ISSUE THREAD

**Issue by tleon** [PrestaShop/open-source#198]
Hello everyone, 

My name is Thomas, and I've been working for Prestashop SA for the past couple months. 

I had the chance to approach various topics, like the core of PS, some modules, and work on the new api. While I'm still getting acquainted with the project, I feel like every day I learn more and more about it. I have been doing some review, bug fixing, and trying to interact more and more with the members of this community. This is why I think I can finally ask you all to welcome me into the committer team. 

It would be a great honor for me, and I would be glad to continue doing what I enjoyed doing these past months alongside you all.

Thanks for the time you took reading me. 

Have a good day.

**Comment by matthieu-rolland** [comment]
One approval here 👍

**Comment by kpodemski** [comment]
Second approval.

**Comment by jolelievre** [comment]
And a third one!!

**Comment by jolelievre** [comment]
Welcome aboard @tleon !! 🎉
