### ISSUE TITLE
[Request to become a PrestaShop committer] ga-devfront

### ISSUE THREAD

**Issue by ga-devfront** [PrestaShop/open-source#199]
Hello everybody,

My name is Alexis and I work for @PrestaShopCorp for almost 1 year.
I am in a team that is very interested in the OpenSource project, in particular hummingbird and everything related to the themes.
I have already made several PR which have been validated whether on the [PrestaShop project](https://github.com/PrestaShop/PrestaShop), the [documentation](https://github.com/PrestaShop/docs) or [Hummingbird theme](https://github.com/PrestaShop/hummingbird) :
- https://github.com/PrestaShop/PrestaShop/pull/32152
- https://github.com/PrestaShop/docs/pull/1422
- https://github.com/PrestaShop/hummingbird/pull/362
- https://github.com/PrestaShop/hummingbird/pull/514
- https://github.com/PrestaShop/hummingbird/pull/495

I had the chance to discuss in detail the future of this magnificent OpenSource project with other members of the community and I would like to continue this adventure as a committer if you accept me.

I thank you in advance for having read me and I would not hesitate to answer your slightest questions.

Good day !

**Comment by kpodemski** [comment]
You have my vote :)

I'll also ping some other people who may be interested in voting.

@Hlavtox @SharakPL

**Comment by Hlavtox** [comment]
I agree!

**Comment by matks** [comment]
Hello I checked your work on Hummingbird and it's good 😉 so it's a YES for me (I feel like I'm a judge in America Got's Talent)

**Comment by kpodemski** [comment]
Welcome aboard @ga-devfront 🎉 
You are now officially a PrestaShop Project committer :)
