### ISSUE TITLE
[Request to become a PrestaShop committer] tblivet

### ISSUE THREAD

**Issue by tblivet** [PrestaShop/open-source#200]
Hi everyone 👋

My name is Thibault, I work for PrestaShop since exactly 1 year has Front Integrator !
I'm very interested in PrestaShop theming, and I've worked on creating PrestaShop themes in my previous jobs in web agency.

I love the work that has been done on hummingbird, that's why I'm happy to ask you to be a PrestaShop committer and be part of the adventure if you accept me.

Thanks in advance for reading, and don't hesitate to ask me if you have any questions.

Have a nice day !

**Comment by kpodemski** [comment]
Hello @tblivet 

It would be great to have you as a committer, but I'd love to see some activity coming from you in the project's public space so that others can also see your input. Without it, it wouldn't be fair to others to accept your application at the moment.

**Comment by tblivet** [comment]
Hello @kpodemski,

Yes I agree with you, I'm new about contributing to the project, here you can find a fresh in progress contribution.
https://github.com/PrestaShop/hummingbird/pull/524

**Comment by tblivet** [comment]
Hi @kpodemski, I'm still interested in being a committer !
Do I have something to do, like added more contributions or something else ?

**Comment by matks** [comment]
@tblivet has now a nice record of merged PRs https://github.com/pulls?q=is%3Apr+author%3Atblivet+org%3Aprestashop+archived%3Afalse+is%3Aclosed

I vote YES for him to become a committer 😉

**Comment by kpodemski** [comment]
You have my vote @tblivet

**Comment by Progi1984** [comment]
:notebook: PrestaShop Committer in Tech Council or in Quality Council ?

**Comment by tblivet** [comment]
Hello @Progi1984 my request is for PrestaShop Committer in Tech Council 😀

**Comment by matthieu-rolland** [comment]
yes 👍

**Comment by kpodemski** [comment]
Congratulations @tblivet - you now join committers team :)

**Comment by tblivet** [comment]
Thank you all 🙏
