### ISSUE TITLE
[Request to become a PrestaShop committer] M0rgan01 

### ISSUE THREAD

**Issue by M0rgan01** [PrestaShop/open-source#209]
Hello everybody :)

I am writing to you today to express my interest in becoming an active contributor within the open source project.
Having followed the development of the project with great interest and being passionate about the field,
I am convinced that my contribution could bring real added value to the team.

My name is Morgan, and I have been contributing to the Prestashop project since early May as a passionate developer.
I have a strong background in software development, particularly in automated testing, application deployment in production environments, and software design and architecture.

As a current contributor, I have already been actively involved in project by submitting pull requests,
by solving problems and helping other members of the community.
I am also aware of the importance of maintaining clean and well-documented code.

Thank you sincerely for considering my application, and I hope to have the opportunity to actively contribute to the open-source project as a committer. 
I am confident that my passion, experience, and dedication will be valuable assets to the project.

**Comment by matks** [comment]
I approve this application 😉 I think we can add to your application
- your contributions https://github.com/pulls?q=org%3APrestaShop+is%3Apr+author%3AM0rgan01
- your code reviews https://github.com/M0rgan01

**Comment by matthieu-rolland** [comment]
I aprove too 👍

**Comment by jolelievre** [comment]
Ok for me as well.

**Comment by matks** [comment]
Dear @M0rgan01 I quote [the maintainer guide](https://www.prestashop-project.org/maintainers-guide/how-to-become-a-committer/):

> If three maintainers approve the application, the new committer is approved.

You are consequently approved as committer, welcome in the team!
