### ISSUE TITLE
Write about the new testing suite

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/open-source#21]
When the new testing suite will be available, write about it asap in order to show the work done, the improvements, and what still needs to be done.

The testing suite is the key to improve the overall quality of the software and reduce regressions.

See also #20

**Comment by matks** [comment]
I think we have explained quite well all different tests in https://devdocs.prestashop.com/1.7/testing/

**Comment by ttoine** [comment]
ok.
Enabling QA for external people is another step.
