### ISSUE TITLE
[Request to become a PrestaShop issue manager] hlavtox

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/open-source#215]
Hi guys,

I would like to help with managing the issues from time to time. 

### What I would like to do
- Help extract more information from the people.
- Adjust the majority of some issues.
- Close some nonsense issues that are not bugs, to save time of testers and other issue managers.
- All of this without upsetting the QA team. :-))))

### Why say yes
- I know the code inside out, I know the logic and the expected behavior.
- Nearly 1000 contributions for the project and several years of experience.

**Comment by Hlavtox** [comment]
@AureRita @boubkerbribri Hi, I will reply to the failed points.

> The contributor follows the project’s Code Of Conduct -> ❌ You often make fun of the QA team as we can see in your presentation, You don't trust the judgments of the different members of the QA team, you even allow yourself to insult their work, if you want screens, I can provide them .

Provide, please.

> The contributor knows the difference between a bug and a feature -> ❓ You never wanted to work with us so we don't know if you know the difference

Do you think that as a member of tech council, product council and more than 400 PRs merged I don't know a difference between a bug and a feature?

> The contributor is aware of testing ❌ We have already offered you to do a day as testers and issue manager. You refused, saying that you knew how to do this job better than we did.

I know all the testing procedures (CI and ga.tests.ui.pr) I need for opening, managing and testing PRs. If you have some more internal tests, I can't know about them.

> The contributor has tested PRs (other than his/her own) ❓ We know you're reading the code and looking for anomalies in it, but we don't know if you're trying the code on the software.

You may have missed it, but I have tested many PRs that required dev QA. Example - https://github.com/PrestaShop/PrestaShop/pull/29922#issuecomment-1343554044


### I think I can be a great help to the team as we could polish some friction points between QA team and the community. These are some points I gathered. 👍

- Testers don't read/understand PR and issue descriptions properly. (for example faceted search PRs)
- Testers don't look into the code at all, they should have at least some basic knowledge. (https://github.com/PrestaShop/PrestaShop/pull/31300)
- Testers don't do basic troubleshooting and provide is with required information. Did module update solve the issue? Did clearing cache solve the issue? They could also provide us with a database dump (few megabytes) so we can check what is happening there. (https://github.com/PrestaShop/PrestaShop/issues/31659)
- Testers report a "white screen" error. https://github.com/PrestaShop/PrestaShop/issues/31945#issuecomment-1486606148
- Testers close issues without having a clue what its about. (https://github.com/PrestaShop/PrestaShop/issues/31649)
- Testers change issue names without having a clue what its about. (https://github.com/PrestaShop/PrestaShop/issues/31593)
- Testers blindly check everything because of one change. Not efficient at all. You change a logo in a backoffice header and they will check all backoffice pages.
- Testers mark issues as duplicates without even reading them at all, just by a name simmilarity. They even say to the contributor "Can you check if these are simmilar?"... For example - they just link all issues having faceted search in their name.
- Testers often have problems understanding easy issue written in perfect english. Read the issue and look at the video how it was tested. https://github.com/PrestaShop/PrestaShop/issues/30074
- Testers are completely ignoring people comments and doesn't even try to check if the comment is valid. https://github.com/PrestaShop/PrestaShop/issues/30026 or https://github.com/PrestaShop/PrestaShop/issues/30024
- Testers report missing translation as an issue. Even when you tell them. https://github.com/PrestaShop/PrestaShop/pull/31322#pullrequestreview-1332542087
- Testers disrespect other contributors, consider their opinion irrelevant and ping company people instead. https://github.com/PrestaShop/PrestaShop/pull/31729#issuecomment-1488426907
- Testers report things like "Templates are now sorted A-Z instead of completely randomly" as an issue - https://github.com/PrestaShop/PrestaShop/pull/31504#pullrequestreview-1320164347
- Communication issues - Release PR has a conflict and testers can't test it. I text the manager if they can test it just by cloning it. OK. Next person comes and reports the same problem and failed QA. I text manager again. OK. Guess what the third QA person reports to me in DM? https://github.com/PrestaShop/statsstock/pull/24
- Performance of the QA team - 1 PR for 4 hours on average. When I ask why it took 5 hours to test a simple PR, they say that 2 hours was lunch.

**Comment by matthieu-rolland** [comment]
You managed to turn your application into a full prosecution against the QA team.

Honestly, I was about to approve it, but I'm really afraid that by letting you intervene at this level, we will generate even more toxicity.

I clicked randomly on one of your "gathered evidence that QA is bad" and reading the conversation I see you saying things like `@florine2623 Do the QA please and don't question it` and then expecting them to be nice and comply with your orders.

You don't talk to them as you would with collaborators, but rather as if they were subordinates, and that is a huge problem.

**Comment by kpodemski** [comment]
Of course, I'm voting yes. On one condition. Even when you are frustrated, you should keep it to yourself. We discussed it. It is sometimes frustrating, but you have to be calm and respectful :-)

I would like to respond to some of the messages above. As someone who works closely with Daniel and often struggles to understand certain actions taken by QA, I feel it is important to speak up.

@boubkerbribri 
> You are not "Quality assurance" mature enough to apply to this role.

You're writing like issue management would be rocket science. That's one thing, the other is that you guys follow processes, you can share them with Daniel. He is part of the technical and product council, he can have a much better perception of whether something is a real issue, a feature request, or just a question than most QA members.

> You don't follow the rules of the issue manager process

I know Daniel has made some mistakes with labels, I've made some too. Issue managers as well. I don't think it is equal to not following the rules.

@AureRita 
> The contributor knows the difference between a bug and a feature -> ❓ You never wanted to work with us so we don't know if you know the difference

That's absolutely ridiculous. 

> The contributor is aware of testing ❌ We have already offered you to do a day as testers and issue manager. You refused, saying that you knew how to do this job better than we did.

The issue manager has steps to reproduce, right? If she/he doesn't, the issue is invalid. What special set of skill sets does it require exactly?

> The contributor has tested PRs (other than his/her own) ❓ We know you're reading the code and looking for anomalies in it, but we don't know if you're trying the code on the software.

I'm pretty sure Daniel tested a lot of PRs, a lot from "Waiting for a dev" to helping @hibatallahAouadni and others follow new scenarios. How could you say that you don't know if he's tested the code on the software? 🤯 

@matthieu-rolland 
> You managed to turn your application into a full prosecution against the QA team.

I don't see it that way. I know Daniel has his attitude, but he wants the best for the project, and he provides it. He raised valid points which have to be finally discussed. The timing is a little off, Daniel probably went full defensive mode, but it is understandable given the reasoning I see above.

**Comment by boubkerbribri** [comment]
@matthieu-rolland @kpodemski I appreciate your comments but unfortunately your votes does not count.
The Issue manager role is an assigned role from Quality council and only his members can vote. The decision made can be override only by the Lead Quality council and the Project lead.

PS: This doesn't mean you can't express your opinion, we are happy to take it under consideration.

**Comment by Hlavtox** [comment]
> You managed to turn your application into a full prosecution against the QA team.

@matthieu-rolland That's not true, I don't have anything against anybody personally. I just want to resolve some friction points that are driving community members away. I tried to raise these points several times to several people from the management, but not a single change was done. Everything is working fine, there is no problem, leave us alone. When you try to make a change, suggest something, say that this could be done better, you get an answer that you are dishonesting the work of the QA team.

What professionalism is that? Where do we move forward? Why on office hours it's me, product manager and core developers discussing how to better manage the issues?

Regarding my attitude you may feel - You would not go into defensive mode, when somebody would tell you that you don't know a difference between a bug and a feature, or, that you have never tested a PR?

@AureRita I think you have very short term memory, you must have forgot that it's not even a year back when I spent hours calling you and helping you test image generation PRs, when you did not even know how to check if an image is a JPG or PNG. Gratitute at it's best.
