### ISSUE TITLE
[Request to become a PrestaShop committer] ShaiMagal 

### ISSUE THREAD

**Issue by ShaiMagal** [PrestaShop/open-source#231]
Hi guys,

I would like to be committer, I am working with PrestaShop since 2012 (approximatelly).
I know history of this project from version 1.4. Long way.....

I am working most of time on my own private projects:
 - https://www.openservis.cz/ - Specific PrestaShop Webhosting focused on performance
 - https://psmoduly.cz/ - PrestaShop modules, more than 200 PS modules on my scoreboard.
Both of there services are related primary to customers from Czech Republic and Slovak Republic.
 - I publish regularly blog posts for free about PrestaShop in Czech language - tips, tricks -> now nearly 200 blog post in time (https://www.openservis.cz/prestashop-blog/)
 
 - [I made a few PRs already](https://github.com/PrestaShop/PrestaShop/pulls?q=author%3AShaiMagal) + a few PRs for other modules (autoupgrade, gsitemap, ...)
 - [I reached security team with critical vulnerability 2022/07](https://build.prestashop-project.org/news/2022/major-security-vulnerability-on-prestashop-websites/), I actively monitor my customer websites and alert them to security issues and helping with solving problems
 - I am helping my customers with PrestaShop eshop update to provide better security

I have a lot of experiences with PrestaShop and I think, I can be right wind for this project.
Especially because i know REAL issues, REAL complains and REAL use cases of hundreds PrestaShop customers (e-shop owners), because I host their eshops and they write me, if they have any issues or questions about PrestaShop.

Like hosting provider (for PrestaShop only) I have a lot of feedbacks from customers about PrestaShop and their opinion of development and future of PrestaShop project.

Also worth mentioning we are friends with @Hlavtox looong time (we live in same city) and in past I told Hlavtox about PrestaShop and we move his eshops to PrestaShop from other platform, good choise I think! :)
So, I already got one great person for this project in the past :-D

**I would like to invest some of my time in this open source project, especially to review PRs and make work smooth with PR approval and eliminating any "bad code" in core.**

Looking forward to get your feedback! :)
Dominik.

**Comment by Hlavtox** [comment]
Obviously a strong YES for me. It would be awesome to have a veteran on board. 😁 There is not a problem or piece of code you didn't see.

Quite a turn around when not long ago, I was convincing you just to create an issue, and now you are actively helping people and creating PRs. 🙏

**Comment by matks** [comment]
> Quite a turn around when not long ago, I was convincing you just to create an issue, and now you are actively helping people and creating PRs. 🙏

Reminds me of someone 😏

**Comment by kpodemski** [comment]
You have my vote 👍🏻

**Comment by M0rgan01** [comment]
Considering the latest contributions and experience on the project, it's ok for me.

**Comment by matks** [comment]
I quote [the maintainer guide](https://www.prestashop-project.org/maintainers-guide/how-to-become-a-committer/):

> If three maintainers approve the application, the new committer is approved.

("maintainer" is the old title for members of the technical council)

You are consequently approved as committer, welcome in the team! ❤️

**Comment by boherm** [comment]
Welcome aboard @ShaiMagal! 😉

**Comment by matthieu-rolland** [comment]
that's a yes for me too 👍

**Comment by ShaiMagal** [comment]
Thank you guys for warming welcome! :)
