### ISSUE TITLE
Access to prestashop source documentation

### ISSUE THREAD

**Issue by DrjavaB** [PrestaShop/open-source#238]
Subject: Request for Permission to Access Company Documents

Dear Prestashop manager,

I hope this letter finds you well. I am writing to formally request permission to access the documents and records of your esteemed project.

As we develop prestashop project for own company, I believe that accessing these documents will greatly assist me in get our goals. The information contained within these documents will contribute significantly to my research, analysis, and understanding of prestashop requests life cycle and mechanism .

I assure you that the information obtained will be used solely for the purposes stated above and will be treated with the utmost confidentiality. I understand and respect the sensitive nature of the documents, and I will adhere to any security protocols or restrictions imposed by your project.

If granted access, I will strictly abide by any terms and conditions set forth by your project regarding the use, storage, and sharing of the documents. I will take full responsibility for any damages or breaches that may occur during my access to these materials.

I kindly request that you grant me access to the relevant documents for a specified period of time. Additionally, if there are any fees or administrative procedures associated with this request, please let me know so that I can fulfill them accordingly.

Thank you for considering my request. I sincerely appreciate your time and attention to this matter. I look forward to your positive response.

Yours faithfully,

Hossein Raad (drjavab)
[linkedin](https://www.linkedin.com/in/drjavab/)

**Comment by DrjavaB** [comment]
we need developer document to contribute source code
can we access to this docs please?
thank you for your attention.

**Comment by matks** [comment]
Hello @DrjavaB we will not give you access to documentation because the documentation is already available, for free, for everyone. It is hosted on https://devdocs.prestashop-project.org/ . There is no other documentation.

Your request for permission to access documents is not needed, because all these documents are already accessible, to everyone, on Internet.
