### ISSUE TITLE
[Request to become a PrestaShop maintainer in Quality Council] Progi1984

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/open-source#241]
Hello Quality Council,

As a Software Developer in Test for over a year (committer), and previously a maintainer on the Tech Council, I would like to join the Quality Council to allow to my voice to be a part of new decisions in the quality of the project.

I have been involved in many aspects of the project: 
* Review PRs of UI tests
* Create new UI tests and maintain old ones
* Adapt the UI tests with the new features of the application and all versions from PS 1.7
* Ensure the quality of tests by the continuous evolution
* The monitoring of the nightly (Fixing problems and finding bugs)
* Run all campaigns on same pull request and fix the errors
* Testing and validation of PRs
* Testing and validation of modules

I hope you will find in these words the conviction to crown me with the role of maintainer !

Thanks for all

**Comment by boubkerbribri** [comment]
It's about time :laughing: .
I can just say that I love it, I will personally be happy if you join the quality council.
The Quality Council has started the session vote as from today, and we will report the decision very soon.

**Comment by sallemiines** [comment]
Best Luck @Progi1984 ! you deserve to be a PrestaShop maintainer in Quality Council :muscle:

**Comment by boubkerbribri** [comment]
We have Reached 8 :white_check_mark: on 11, we can welcome Franck as a @PrestaShop/ui-tests-maintainers and part of Quality Council

**Comment by Progi1984** [comment]
Thanks the team :tada:
