### ISSUE TITLE
[Request to become a PrestaShop committer] mattgoud

### ISSUE THREAD

**Issue by mattgoud** [PrestaShop/open-source#266]
Hello everyone 👋

My name is Matthias,  and I’ve been working at PrestaShop as a front-end developer for over 2 years.
Recently, I joined the software team to tackle issues and enhance the front-end solution.
I’m also involved in the development of [Puik](https://github.com/PrestaShopCorp/puik) (the new PrestaShop UI Kit).

I greatly admire the team’s work, which is why I’m excited to apply to become a PrestaShop contributor and be part of this journey, if you’ll have me.

Thank you in advance for your consideration, and feel free to ask me any questions.

Have a wonderful day! 😊

**Comment by matks** [comment]
I think we can also include your record of merged PRs 😉 https://github.com/pulls?q=is%3Aopen+is%3Apr+author%3Amattgoud+org%3Aprestashop

**Comment by nicosomb** [comment]
https://github.com/pulls?q=is%3Apr+author%3Amattgoud+org%3Aprestashop+is%3Aclosed this link seems to be better.

**Comment by LouisAUTHIE** [comment]
Cool, welcome

**Comment by mattgoud** [comment]
> Cool, welcome

Thanks @LouisAUTHIE

**Comment by mattgoud** [comment]
> I've been working with you since you joined the team so obviously I approve this 😉

Thanks @matks

**Comment by jolelievre** [comment]
Welcome aboard @mattgoud it will be good to have a frontend committer 😉

**Comment by kpodemski** [comment]
Welcome 👍🏻

**Comment by mattgoud** [comment]
> Welcome aboard @mattgoud it will be good to have a frontend committer 😉

Thanks @jolelievre

**Comment by mattgoud** [comment]
> Welcome 👍🏻

Thanks @kpodemski

**Comment by matks** [comment]
Dear @mattgoud  I quote [the maintainer guide](https://www.prestashop-project.org/maintainers-guide/how-to-become-a-committer/):

> If three maintainers approve the application, the new committer is approved.

You are consequently approved as committer, welcome in the team!
