### ISSUE TITLE
Définir quelle licence utiliser pour le projet "specs"

### ISSUE THREAD

**Issue by sam-pires** [PrestaShop/open-source#36]

**Comment by ttoine** [comment]
To solve that, just create a licence.md file, with the text of the license:
https://creativecommons.org/licenses/by-sa/4.0/legalcode

A plus would be to add "CC BY-SA 4.0 - https://creativecommons.org/licenses/by-sa/4.0/" in the specs files. But having a licence.md file and configure it in the repository config is the must have.

**Comment by sam-pires** [comment]
Done 
https://github.com/PrestaShop/prestashop-specs/pull/116

thks @ttoine 👍

**Comment by ttoine** [comment]
merci.
