### ISSUE TITLE
I want to become a PrestaShop Core maintainer

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/open-source#48]
**I am Julius. Web developer from Lithuania.**

**I would like to become a maintainer of PrestaShop Core :stuck_out_tongue:**

**Background**

I am working with Prestashop migration to Symfony for almost 2 years now.
During those years I've developed quite some knowledge of PrestaShop technical specifics as well as good communication with PrestaShop team.
Even when I am not working on Prestashop migration, I develop modules/custom solutions to help merchants succeed. So I always stay close to PrestaShop and improve my technical & E-commerce domain knowledge.

**Why**

I hope becoming a maintainer would allow to speed up migration process, especially during product page migration & other pages where it requires working in little focused teams. It would allow to merge PR's faster and remove some workload from other members.

**Comment by matks** [comment]
Hi @zuk3975  and thank you for your application 😄 

Following [our rules](https://devdocs.prestashop.com/1.7/project/maintainers-guide/how-to-become-a-maintainer/), now can start discussions with current maintainers on this issue about your application 😉 

Well, you and us know each other so maybe there won't be a lot of questions 😁 ! let's see

**Comment by PierreRambaud** [comment]
> I hope becoming a maintainer would allow to speed up migration process, especially during product page migration & other pages where it requires working in little focused teams. It would allow to merge PR's faster and remove some workload from other members.

Hi and thanks for your application.
The review is already something you can do right now. 
Why do you consider the merge process is not fast enough? 
How fast should be a review and a merge for you? 

There are a lot of things to do on PrestaShop, not only related to the migration, regarding your message, it looks like you only want to focus on your colleagues, am I right?

**Comment by zuk3975** [comment]
Thanks for questions

> The review is already something you can do right now.

Indeed. And I do from time to time (if I feel confident about that topic). But I cannot help when some perfect little PR is missing an approval, that's where I believe I could speed up things sometimes. 
I'm aware it brings great responsibility, so I'm not planning to approve any PR's until I'm sure its right.

> Why do you consider the merge process is not fast enough?

Sometimes it lacks of approvals (can happen for many reasons: vacations, PS events, complicated topic etc..) and in time PR's gets stuck in a loop of conflicts-resolving & approving & testing. So Its not like I will solve it, but rather it is improving by each new maintainer. That is especially visible in product page migration, when only 2 of us code, but only one has the rights to approve, so most of the time we need to ask other members to dig into complex code over and over again, which costs a lot of time. Once again, Its not always a drawback, as those members spots some problems and raises some questions from aside, but in some situations little and clear PR is blocking something and it stops whole process because single approval is missing :stuck_out_tongue: 

> How fast should be a review and a merge for you?

Cannot rush the merge for sure, as it's risky to introduce something wrong, but can't wait to much especially on blocking PR's too. So I agree it's not an easy process. I can't say what is a fast merge, but merges speed could at least improve on PR's that are clear and has no questions. I'm aware that core members have lots of work to do besides merging, so once again, that's were maintainers can help :P

> There are a lot of things to do on PrestaShop, not only related to the migration, regarding your message, it looks like you only want to focus on your colleagues, am I right?


Well, I'm not gonna lie, my focus right now is to speed up product page migration, but I'm not saying that It ends up here.
And Im not focusing on my colleagues, rather I meant PrestaShop Core team :)

**Comment by PierreRambaud** [comment]
Thanks for your answers!

> so most of the time we need to ask other members to dig into complex code over and over again, which costs a lot of time

It costs time but it allows everyone to take part in the migration and regarding what happened on the Order page, it's a benefit because many of us had to fix a bug on it :( 

> but in some situations little and clear PR is blocking something and it stops whole process because single approval is missing

You should know, even a little PR with one word can break PrestaShop. Sometimes little PRs are really harder to review and to tests.

> can't wait too much especially on blocking PR's

Unfortunately, this is a normal process in the open-source ecosystem, and fortunately, we have enough work to do to be able to wait a few days and begin another task, even on the Product page. And if not, there are many others things to do related to the migration.

> I'm aware that core members have lots of work to do besides merging, so once again, that's were maintainers can help :P

Core members are also maintainers and the maintainer role is not only for review & merge.
Maintainers are also technical references and must review all Pull requests.

For example, you did a pull request about [supplier reference](https://github.com/PrestaShop/PrestaShop/pull/20544#discussion_r470054862) if it was review and merge too fast, a regression could have been introduced. It always a bad idea to have only the same people reviewing and merging ^^'

**Comment by zuk3975** [comment]
I agree :man_shrugging:
