### ISSUE TITLE
Fatal error: Uncaught PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException: No decimal pattern found for numbering system: 

### ISSUE THREAD

**Issue by innocenceesstt** [PrestaShop/open-source#54]
my website works in my local server but when i migrated to ovh server i have this error 
![image](https://user-images.githubusercontent.com/24615640/109729058-a1e05f80-7bb7-11eb-8492-94b9c135e162.png)

when i deleted the var/cache content i had these warning 
Warning: simplexml_load_file(): I/O warning : failed to load external entity "" in /home/vrqlcrq/www/src/Core/Localization/CLDR/Reader.php on line 152

Warning: simplexml_load_file(): I/O warning : failed to load external entity "" in /home/vrqlcrq/www/src/Core/Localization/CLDR/Reader.php on line 162

Notice: Trying to get property 'parentLocales' of non-object in /home/vrqlcrq/www/src/Core/Localization/CLDR/Reader.php on line 212

Notice: Trying to get property 'parentLocale' of non-object in /home/vrqlcrq/www/src/Core/Localization/CLDR/Reader.php on line 212

Warning: Invalid argument supplied for foreach() in /home/vrqlcrq/www/src/Core/Localization/CLDR/Reader.php on line 212

Notice: Trying to get property 'parentLocales' of non-object in /home/vrqlcrq/www/src/Core/Localization/CLDR/Reader.php on line 212

Notice: Trying to get property 'parentLocale' of non-object in /home/vrqlcrq/www/src/Core/Localization/CLDR/Reader.php on line 212

Warning: Invalid argument supplied for foreach() in /home/vrqlcrq/www/src/Core/Localization/CLDR/Reader.php on line 212
Help me please

**Comment by ttoine** [comment]
sorry this is not the place to report issue, or ask for support. please use the forums, or the prestashop repository.
