### ISSUE TITLE
Prestashop 1.7.7.4 problem with invalid token

### ISSUE THREAD

**Issue by matypresta** [PrestaShop/open-source#58]
after uploading the modules to the prestashop, an invalid security token error popped up, it is no longer possible to click on uploading the module does not respond.  Don't know what it can be?  I tried PHP changes to clear cache, other browsers.  but it doesn't work, please advise.

**Comment by matypresta** [comment]
instructions from the page:  https://github.com/PrestaShop/PrestaShop/commit/84eaa4f9cbb773dc481f3cf84f63db1a7d253827 
does not work I can not eat the file: controllers/admin/AdminCmsController.php
And
controllers/admin/AdminCmsCategoriesController.php 
Not found in FTP server.

**Comment by matks** [comment]
If you have questions or need help, please do not open a GitHub issue as we use GitHub issues only to discuss about bugs and new features for the PrestaShop project.

You will find better places to ask questions on https://devdocs.prestashop.com/1.7/faq/i-need-help/
