### ISSUE TITLE
additional group discount doesn’t show in front office 

### ISSUE THREAD

**Issue by nossanhendel** [PrestaShop/open-source#59]
I am struggling for a few hours on this problem I will be very happy if you can help me out with this..

I need to make another group besides customers that will get 10% off on all the store

The problem is when I add the new group and I put a discount, the customers from this group don’t see any discount..
When I put discount for all customers it’s working but any additional group doesn’t work.

I know how to make discount for different groups and it works perfectly fine, The problems start with additional groups more then The three groups of visitor guest and customers, and with a catalog discount.
in the functionality of prestashop add groups, after I add a group with catalog discount for this specific group.
When the customer from this group will log in it doesn’t display the discount.

I would like to add screenshot so you understand.. 
thank you very much

https://screencast-o-matic.com/watch/cr1Q6hVhJJF

**Comment by matks** [comment]
Hello, if you have questions or need help, please do not open a GitHub issue as we use GitHub issues only to discuss about bugs and new features for the PrestaShop project.

Please follow https://devdocs.prestashop.com/1.7/faq/i-need-help/ to find the right place to get help
