### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by matks** [PrestaShop/open-source#63]
https://www.prestashop-project.org/ uses standard favicon, maybe a prestashop favicon would be pretty?

**Comment by ttoine** [comment]
good idea. do you know how to do it ?

**Comment by matks** [comment]
On Build it's in the root folder https://github.com/PrestaShop/prestashop.github.io/blob/master/favicon.png
On devdocs it's configured by hugo https://github.com/PrestaShop/docs/blob/master/src/layouts/partials/favicon.html
