### ISSUE TITLE
Add Public OSS Demos schedule and content

### ISSUE THREAD

**Issue by matks** [PrestaShop/open-source#66]
Hello, would it be a good thing to add a area on https://www.prestashop-project.org/ that would
- provide the list of past [Public Demos](https://build.prestashop.com/news/first-public-oss-demo/)
- provide the schedule of incoming Public Demos and (when it's definitive) the content

What do you think ?

**Comment by matks** [comment]
wdyt @eternoendless @ttoine

**Comment by eternoendless** [comment]
I think that sounds more like something for Build, right?

**Comment by matks** [comment]
> I think that sounds more like something for Build, right?

It can also go on Build indeed.

**Comment by matks** [comment]
I close as this is not the right place.
