### ISSUE TITLE
[Request to become a PrestaShop maintainer] Boubkerbribri

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/open-source#68]
## About me
I’m Boubker, 29 years old and I’m a QA automation Lead at the PrestaShop company.

## The beginning
Back in 2019, when I first discovered the project, I didn’t know much about Open-source (yeah, I did the mistake `open-source = free of charge`). 
Then I joined the team and discovered an entirely different context and concept, full of love, commitment and collaboration.

## Why?
As a member of the QA team, and with the help of the team, I’m responsible for:

- Create new UI tests and maintain old ones.
- Ensure the quality of tests to be 100% reliable.
- Analyse tests outcome for nightly builds.
- Analyse tests outcome on CIs (on different projects).
- Update tests dependencies.
- Run all campaigns on some pull requests.

### So why become a maintainer?

I could think of 3 reasons to become a project maintainer :

1. It’s the consequence of what I’m doing right now, to ‘Ensure the quality of tests’, I have to review more PRs linked to tests.

2. As a contributor, I’m committed to the Project’s improvement. As a maintainer, My commitment will not be just for the project, but also for contributors. It will help me discuss with them the improvements, how to add tests, adding documentation …

3. Becoming a Maintainer will also open up the possibility to add and maintain more tools for contributors, for example, The new modules testing library that should be open source soon.

## Some numbers

You can find the details about my contributions [here](https://contributors.prestashop.com/#boubkerbribri).

![image](https://user-images.githubusercontent.com/48441421/136206969-c90f87f0-afd8-41be-b252-70e07f5e069f.png)

**Comment by matks** [comment]
Hi @boubkerbribri  and thank you for your application 😄

Following our [rules](https://devdocs.prestashop.com/8/project/maintainers-guide/how-to-become-a-maintainer/), now can start discussions with current maintainers on this issue about, among other things, your motivation and skills about the project.

Well, you and us know each other so maybe there won't be a lot of questions 😁 ! let's see

**Comment by kpodemski** [comment]
No questions from my side either, we don't have anyone with your specialty in the team, so I'm sure you would bring significant value to the team!

**Comment by Progi1984** [comment]
No questions from my side. That's a +1 for me!

**Comment by matks** [comment]
Modules
Internal tools like docker images https://github.com/prestashop/docker or https://github.com/prestashop/core-weekly-generator
UI kit https://github.com/prestashop/prestashop-ui-kit

**Comment by PrestaEdit** [comment]
👍 for @boubkerbribri as tests-mainteners !
👍 for maintener-roles !

**Comment by eternoendless** [comment]
Hi @boubkerbribri 

Sorry for the very long delay. Your original request took us off guard because we had originally meant the maintainer concept as a one-size-fits-all role for developers. We never thought about how it would work for specific roles like QA automation.

Since then, our understanding of the subject has evolved. We created the roles of **committer** and **scoped maintainer**, but they only address part of these issues. There's still a lot of work to be done to clarify how decisions are made and by whom. However, since you have been leading the development for UI tests for years now, I think it would make perfect sense to name you scoped maintainer for UI tests.

What do you say?

**Comment by boubkerbribri** [comment]
Hi @eternoendless, yes I'm ok with the role and it will fit me and SDT(s) better.
Thanks.

**Comment by eternoendless** [comment]
The maintainers have voted. I have the pleasure to welcome you into the maintainers group @boubkerbribri :)

**Comment by boubkerbribri** [comment]
Thanks All :smile:
