### ISSUE TITLE
Improve discussion platforms for the community

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/open-source#7]
Discussion platform are not that great currently to foster and grow a community. A few actions have been identified.

Moving every technical discussion to GitHub will allow to have all in the same place, and within the same application. This will greatly simplify the life of developers who are opening pull requests, and linking them to issues.

The forum was abandoned: no moderation, a lot of technical issues, security upgrades to be done, spam and trolls, and many more issues to fix to attract people again, and gain trust from its users.

All active open source project have a Chat. It used to be on IRC, mostly on freenode.org, but today the ecosystem use a lot "Slack". It is time for the PrestaShop community to have a Slack, to be used by developers, contributors, users, and all its personas to exchange.

1.  [x] move technical discussion to GitHub
2.  [x] make the forum great again
3.  [x] create a chat for the community

**Comment by matks** [comment]
Hi @ttoine we now have Slack, so can we state this item is done?

**Comment by ttoine** [comment]
Yes, thanks for pointing it.
