### ISSUE TITLE
Improve contribution guidelines and document the review process of issues and pull requests

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/open-source#8]
Many contributors are frustrated to see that their pull request are not merged, or that it takes times to merge.

Many things can be done here:

- [x] [Document priority and severity](http://build.prestashop.com/news/severity-classification/)
- [x] [Document the code review process](http://build.prestashop.com/news/the-review-process/)
- [ ] [Document the pull request prerequisites and show example](https://github.com/PrestaShop/docs/issues/345) (WIP: documentation on how to write tests and other related topics are currently being written)
- [ ] Publish specifications and mockups (WIP -> [PrestaShop/prestashop-specs](https://github.com/PrestaShop/prestashop-specs))
- [ ] Improve the sorting process of issues with projects (improvements are currently being proposed and tested)

**Comment by matks** [comment]
A bit related https://www.prestashop.com/en/blog/prestashop-project-prioritization

**Comment by ttoine** [comment]
https://build.prestashop.com/news/the-new-prestashop-test-framework/
