### ISSUE TITLE
[Request to become a Prestashop maintainer] MeKeyCool

### ISSUE THREAD

**Issue by MeKeyCool** [PrestaShop/open-source#97]
# [Request to become a Prestashop maintainer] MeKeyCool

## About me

I’m Pierre-Yves / Pyc / MeKeyCool, a web developper at Prestashop company.

I am a self-taught developper, starting with "[Site du Zéro](https://fr.wikipedia.org/wiki/OpenClassrooms)" tutorials, I learned C++, php, javascript, scala, rust, ...
I have ten years experience as developper (~6 years as web developper).

I am not the kind of developper spending hours and hours reading rfc, news letters, etc. to be up to date on everything. I prefer to learn things when I need them.
That's why I am currently a bit low with php/javascript/symfony/... (I spend last years to learn scala, rust and devops stuff) but I am strong at learning/understanding new things (even from simply reading code).

For me trust is one of the most important thing for human groups / feelings / society to blossom. I am the kind that think a lot and sometimes I make shortcuts. So please if you are not sure about my idea/intention/goals, never hesitate to ask/critisize because if you think my acts are not consistent with my words, it is probably a misunderstanding ^^

## Why do I want to become maintainer ?

I have always been attracted by open source but I never took the plunge to contribute by my skills (only some donations). Working at Prestashop is a great opportunity for me to discover this ecosystem deeper.

I know that the project isn't the sexiest (technical debt, spaghetti code, ...) but at least I know that I won't get bored with repetitive tasks.

I would find deep satisfaction making things better. So if I have time to solve problems and making things going the right way, I really would feel usefull working on this project :)

Furthermore, I have some personal interests by masterising an e-commerce solution (some of my friends are thinking about building their online business and it would be good if I can help them)

## What can I bring to the project ?

I think I have a good understanding of devops practices and IT usage/sensibility.

The way I would like to contribute is really to help developpers / contributors / tech editors to enjoy using Prestashop (install/update/debug/...).
I have good experiences on old projects with huge technicals debts and I think I can bring ideas and strategies to make migrations better.

I think my technical level is still a bit low for Prestashop requirements (especially with javascript and last symfony versions) but I am making up for the lack and I am used to learn by reading code so it may be a strength for Prestashop.

I think I could bring some "community management" help. I am not always the best diplomatic (euphemism) but I like things well done, good documentation, having a good test coverage on projects, ... I think I am good at linking people. 

## Contributions

I already opened [some PR](https://github.com/pulls?q=is%3Apr+author%3AMeKeyCool+user%3APrestaShop) to Prestashop and participated to [some reviews](https://github.com/PrestaShop/PrestaShop/pulls?q=is%3Apr+reviewed-by%3AMeKeyCool).
Furthermore, I started to involve myself in side projects (hummingbird, fop-console, ...) and I developped my own project for deployment / install tooling : [presta-deploy](https://github.com/MeKeyCool/presta-deploy).

> :point_up: this [presta-deploy](https://github.com/MeKeyCool/presta-deploy) project is a good start to understand my way to think/work. It is not ready to be completly opened but I already have documented it a lot.

If you want to understand me better, you could take a look at [Refactor localisation (#28057)](https://github.com/PrestaShop/PrestaShop/pull/28057).
It is still not merged and I did some mistakes with rebase process (sorry again @jolelievre) but this PR represents quite well my way to search code quality.

One of my biggest review was on [States: migrate add & edit forms(#27987)](https://github.com/PrestaShop/PrestaShop/pull/27987) but I have to admit that past weeks I avoid huge code reviews because I feel useless for most of time and it is quite painful. I think if there no hurry, I'll come back on then when I'll feel more comfortable with codebase.

One contribution I am proud of is [[EPIC] Improve the image system (#27318)](https://github.com/PrestaShop/PrestaShop/issues/27318#issuecomment-1126150180) issue analysis. I would like to imply myself more on this subject (it will be linked to devops questions and it is good to start from clear needs/requirements)

**Comment by matks** [comment]
Hi @MeKeyCool   and thank you for your application 😄 

Following [our rules](https://devdocs.prestashop.com/1.7/project/maintainers-guide/how-to-become-a-maintainer/), now can start discussions with current maintainers on this issue about any topic we wish to explore

Some maintainers are on holidays right now so we will need them to come back so they can have the chance to chat with you before moving on to the voting phase 😉  please be patient 🙏

**Comment by kpodemski** [comment]
Hello @MeKeyCool 

I will be frank with you. I think it's too soon. I'm 100% sure that you'll bring a great value to the project, but for now, it would be hard for me to trust your judgment on "this is good for PrestaShop, and we can merge it", or "this won't have any side effects", etc.

It would be easier if you could show more activity in the project with some quality PRs. From what I see now, you're still in the discovery phase, and in the maintainer's team, we should look for those who can help others discover things :)

Keep up the good work 💪

**Comment by jolelievre** [comment]
I have nothing to add to what @kpodemski said ^^ I share his opinion for now.

**Comment by matks** [comment]
Hello @MeKeyCool I think everyone was able to discuss with you if needed so the vote starts

**Comment by MeKeyCool** [comment]
Thanks for this clear answer @matks .

If you have any other details, feel free to enlighten me about how I can satisfy team expectations.
